# Generated by Django 4.2.1 on 2023-06-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_now_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='now_step',
            old_name='now_step',
            new_name='me_now_step',
        ),
        migrations.AddField(
            model_name='now_step',
            name='other_now_step',
            field=models.TextField(null=True),
        ),
    ]
