# Generated by Django 4.2.1 on 2023-06-06 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_me_now_step_other_now_step_delete_now_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='me_now_step',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AddField(
            model_name='other_now_step',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
