# Generated by Django 4.2.1 on 2023-06-06 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_me_now_step_post_other_now_step_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='me_now_step',
            name='post',
        ),
        migrations.RemoveField(
            model_name='other_now_step',
            name='post',
        ),
    ]
